version: 2
jobs:
  do_SendInfo:
    docker:
      - image: najahi/oven:fedora
    environment:
      is_test: false
    steps:
      - run: git clone https://github.com/gmw-project/kernel_xiaomi_beryllium --depth=1 -b ten .
      - run: echo 'export device="<b>Pocophone F1</b> (Beryllium) Android 10/Q"' >> $BASH_ENV
      - run: wget 
      - run: chmod +x sendInfo.sh
      - run: bash sendInfo.sh
  do_iceshaken:
    docker:
      - image: najahi/oven:fedora
    working_directory: ~/do_iceshaken
    environment:
      is_test: false
    steps:
      - run: git clone https://github.com/gmw-project/kernel_xiaomi_beryllium --depth=1 -b ten .
      - run: wget 
      - run: chmod +x do_iceshaken.sh
      - run: bash do_iceshaken.sh
workflows:
  version: 2
  Continuous-HotOven:
    jobs:
      - do_SendInfo
      - do_iceshaken:
          requires:
            - do_SendInfo
